# Starter pipeline

trigger:
- main

pool: 
    vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@2
  displayName: 'Get secret from keyvault'
  inputs:    
    azureSubscription: 'SUB_Rdam_Management'
    KeyVaultName: 'KVRdamPFManagementDevHIP'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: CmdLine@2
  inputs:
    script: 'echo $(Your-Secret-Name) > secret.txt'