trigger: none
#- main


variables:
-name: azureSubscriptionName
 value: 'Free Trial(036e3d15-5bb2-42bd-9c32-284ecaf1032a)'
- name: tciBaseUrl
  value: 'https://eu.api.cloud.tibco.com/tci/v1/subscriptions/0'
- name: appName
  value: 'FlogoDemoApp'
- name: instanceCount
  value: 1 

stages:
- stage: StageDev
  jobs:
  - deployment: deployOnDev
    pool:
      vmImage: ubuntu-latest
    environment: Development
	strategy:
	  runOnce:
	    deploy:
          steps:  
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(azureSubscriptionName)
              KeyVaultName: 'KVMostafaDemo'
              SecretsFilter: '*'
              RunAsPreJob: false

          - task: Bash@3            
            inputs:
               targetType: filePath
               filePath: flogo_deploy.sh               
               
  
- stage: StageTest
  jobs:
  - deployment: deployOnTest
    dependsOn: deployOnDev
    pool:
      vmImage: ubuntu-latest
    environment: Test
	strategy:
	  runOnce:
	    deploy:
          steps:  
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: $(azureSubscriptionName)
              KeyVaultName: 'KVMostafaDemo'
              SecretsFilter: '*'
              RunAsPreJob: false

          - task: Bash@3            
            inputs:
               targetType: filePath
               filePath: flogo_deploy.sh               
