# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: InvokeRESTAPI@1
  displayName: 'Invoke REST API: GET'
  inputs:    
    serviceConnection: 'TibcoTCIConnection'    
    urlSuffix: '/v1/subscriptions/0/apps/ftwgminksmk3eene3llpzdtk4gce5qrf'
    method: 'GET'
    