# Starter pipeline

trigger:
- main

pool: server

steps:
- task: InvokeRESTAPI@1
  displayName: 'Invoke REST API: GET'
  inputs:    
    connectionType: 'connectedServiceName'
    serviceConnection: 'TibcoTCIConnection'    
    urlSuffix: '/apps/ftwgminksmk3eene3llpzdtk4gce5qrf'
    method: 'GET'  
    headers: |
      {
       "Content-Type":"application/json",
       "Authorization":"Bearer $(token)"
      }
    waitForCompletion: 'true'
    