# Starter pipeline

trigger:
- main

pool: server

steps:
- task: InvokeRESTAPI@1
  displayName: 'Invoke REST API: GET'
  inputs:    
    connectionType: 'Generic'
    serviceConnection: 'TibcoTCIConnection'    
    urlSuffix: '/v1/subscriptions/0/apps/ftwgminksmk3eene3llpzdtk4gce5qrf'
    method: 'GET'  
    #headers: '{\n"Authorization":"bearer ${token}"'  
    waitForCompletion: 'true'
    